### ISSUE TITLE
Could not make it work

### ISSUE THREAD

**Issue by Fastidious** [minilockpostcard/minipost-chrome#1]
I installed the Chrome extension but it did not work. Still working on this? Interested!

**Comment by 45678** [comment]
Hi @Fastidious. i have been away from the computer so i haven’t been working on this.

i am not super interested in this project anymore. but if i can help you sort something out just let me know.

**Comment by Fastidious** [comment]
Not a problem, @45678. I lost my interest as well. Thanks for answering, and for the offer to help!
